volumes:
  metadata-db-data:

services:
  metadata-db:
    container_name: metadata-db
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${METADATA_DB_DATABASE}
      POSTGRES_USER: ${METADATA_DB_USER}
      POSTGRES_PASSWORD: ${METADATA_DB_PASSWORD}
    ports:
      - ${METADATA_DB_PORT}:5432
    volumes:
      - metadata-db-data:/var/lib/postgresql/data
  metadata-db-schema:
    container_name: metadata-db-schema
    image: archi/metadata-db-schema
    build:
      context: db-schema
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://${METADATA_DB_HOST}:5432/${METADATA_DB_DATABASE}
      LIQUIBASE_COMMAND_USERNAME: ${METADATA_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${METADATA_DB_PASSWORD}
    depends_on:
      - metadata-db
